export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const GET_TODO_REQUEST="GET_TODO_REQUEST"
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS"
export const GET_TODO_FAILURE="GET_TODO_FAILURE"